on:
  push:
    branches-ignore:
      - master

name: Protoconf insert to branch
jobs:
  checks:
    name: production
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: insert changes
      uses: protoconf/protoconf-actions@master
      with:
        store_type: consul
        store_address: ${{secrets.CONSUL_ADDR}}
        prefix: ${{ github.ref }}
        changes_only: false
